/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalpcbuild;

import java.awt.Color;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;


/**
 *
 * @author harold
 */
public class Dashboard extends javax.swing.JFrame {

    double total, total2, total3, total4, total5, total6, total7;
    double total1;
    double VCtrack, CPUtrack, Mtrack, Metrack, EHDtrack, WNCtrack;
    double PSUtrack, CPUCtrack;
    public String[] noPrice;
    public static String[] Orderer;
    public int size;
    private JLabel[] order;
    private JLabel[] labels;
    private int currentLabelIndex = 0;
    private int currentLabelIndex1 = 0;
    public double totalPrice = 0.0, totalPrice1 = 0.0 ;
    ArrayList<String> Orders = new ArrayList<>();
    
    

    Color DefaultColor, ClickedColor;

    public Dashboard() {
        initComponents();
        DefaultColor = Color.BLACK;
        ClickedColor = new Color(1, 5, 45);
        BuildaPC.setVisible(false);
        PriceExtimater.setVisible(false);

        labels = new JLabel[]{listing1, listing2, listing3, listing4,
            listing5, listing6, listing7, listing8, listing9, listing10, listing11, listing12,
            listing13, listing14, listing15, listing16};
        
        order = new JLabel[]{order1, order2, order3, order4,
            order5, order6, order7, order8};
     
    }
    
    

    private CPUSelection fileInfo = new CPUSelection();
    private PSUSelection fileInfo2 = new PSUSelection();
    private VCSelection fileInfo3 = new VCSelection();
    private EHDSelection fileInfo4 = new EHDSelection();
    private MSelection fileInfo5 = new MSelection();
    private MeSelection fileInfo6 = new MeSelection();
    private WNCSelection fileInfo7 = new WNCSelection();
    private CPUCSelection fileInfo8 = new CPUCSelection();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jTextField7 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        BuildaPC = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jComboBox9 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        item = new javax.swing.JLabel();
        order2 = new javax.swing.JLabel();
        order3 = new javax.swing.JLabel();
        order6 = new javax.swing.JLabel();
        order1 = new javax.swing.JLabel();
        order8 = new javax.swing.JLabel();
        order4 = new javax.swing.JLabel();
        order7 = new javax.swing.JLabel();
        order5 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        EHDPrice = new javax.swing.JLabel();
        WNCPrice = new javax.swing.JLabel();
        MPrice = new javax.swing.JLabel();
        CPUCPrice = new javax.swing.JLabel();
        MePrice = new javax.swing.JLabel();
        CPUPrice = new javax.swing.JLabel();
        PSUPrice = new javax.swing.JLabel();
        VCPrice = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        TotalP = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Button6 = new javax.swing.JButton();
        Button5 = new javax.swing.JButton();
        Button7 = new javax.swing.JButton();
        PriceExtimater = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        Totalq = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        listing16 = new javax.swing.JLabel();
        listing15 = new javax.swing.JLabel();
        listing14 = new javax.swing.JLabel();
        listing13 = new javax.swing.JLabel();
        listing12 = new javax.swing.JLabel();
        listing11 = new javax.swing.JLabel();
        listing10 = new javax.swing.JLabel();
        listing9 = new javax.swing.JLabel();
        listing8 = new javax.swing.JLabel();
        listing5 = new javax.swing.JLabel();
        listing6 = new javax.swing.JLabel();
        listing7 = new javax.swing.JLabel();
        listing3 = new javax.swing.JLabel();
        listing4 = new javax.swing.JLabel();
        listing2 = new javax.swing.JLabel();
        listing1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        selecteditem = new javax.swing.JLabel();
        Addbutton = new javax.swing.JButton();
        HomePanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Button1 = new javax.swing.JButton();
        Button3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTextField7.setText("jTextField1");

        jLabel23.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BuildaPC.setBackground(new java.awt.Color(1, 1, 34));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Central Processing Unit ");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Video Card");

        jComboBox1.setBackground(new java.awt.Color(1, 1, 64));
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox1PopupMenuWillBecomeVisible(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setBackground(new java.awt.Color(1, 1, 64));
        jComboBox2.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox2.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox2PopupMenuWillBecomeVisible(evt);
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Motherboard");

        jComboBox3.setBackground(new java.awt.Color(1, 1, 64));
        jComboBox3.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox3.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox3PopupMenuWillBecomeVisible(evt);
            }
        });
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Memory ");

        jComboBox4.setBackground(new java.awt.Color(1, 1, 64));
        jComboBox4.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox4.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox4PopupMenuWillBecomeVisible(evt);
            }
        });
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Power Supply Unit ");

        jComboBox6.setBackground(new java.awt.Color(1, 1, 64));
        jComboBox6.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox6.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox6PopupMenuWillBecomeVisible(evt);
            }
        });
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("External Hard Drive");

        jComboBox7.setBackground(new java.awt.Color(1, 1, 64));
        jComboBox7.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox7.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox7PopupMenuWillBecomeVisible(evt);
            }
        });
        jComboBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox7ActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Wireless Network Card");

        jComboBox8.setBackground(new java.awt.Color(1, 1, 64));
        jComboBox8.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox8.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox8PopupMenuWillBecomeVisible(evt);
            }
        });
        jComboBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox8ActionPerformed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CPU Cooler");

        jComboBox9.setBackground(new java.awt.Color(1, 1, 64));
        jComboBox9.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox9.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox9PopupMenuWillBecomeVisible(evt);
            }
        });
        jComboBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox9ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(1, 1, 65));

        item.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        item.setForeground(new java.awt.Color(255, 255, 255));
        item.setText("Items");

        order2.setForeground(new java.awt.Color(255, 255, 255));

        order3.setForeground(new java.awt.Color(255, 255, 255));

        order6.setForeground(new java.awt.Color(255, 255, 255));

        order1.setForeground(new java.awt.Color(255, 255, 255));

        order8.setForeground(new java.awt.Color(255, 255, 255));

        order4.setForeground(new java.awt.Color(255, 255, 255));

        order7.setForeground(new java.awt.Color(255, 255, 255));

        order5.setForeground(new java.awt.Color(255, 255, 255));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Price");

        EHDPrice.setForeground(new java.awt.Color(255, 255, 255));

        WNCPrice.setForeground(new java.awt.Color(255, 255, 255));

        MPrice.setForeground(new java.awt.Color(255, 255, 255));

        CPUCPrice.setForeground(new java.awt.Color(255, 255, 255));

        MePrice.setForeground(new java.awt.Color(255, 255, 255));

        CPUPrice.setForeground(new java.awt.Color(255, 255, 255));

        PSUPrice.setForeground(new java.awt.Color(255, 255, 255));

        VCPrice.setForeground(new java.awt.Color(255, 255, 255));

        jLabel30.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Total :");

        TotalP.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        TotalP.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(order2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(item, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                .addComponent(order1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(order8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                .addComponent(order7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(order6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(order5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(order4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(order3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TotalP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(CPUCPrice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                        .addComponent(MePrice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(WNCPrice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MPrice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EHDPrice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(VCPrice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PSUPrice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(CPUPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(order1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CPUPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(order2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PSUPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(order3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VCPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(order4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EHDPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(order5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(order6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WNCPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(order7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MePrice, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(order8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CPUCPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TotalP, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86))
        );

        jButton1.setBackground(new java.awt.Color(1, 1, 34));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Next");

        jButton2.setBackground(new java.awt.Color(1, 1, 34));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Order");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(1, 1, 65));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        Button6.setBackground(new java.awt.Color(1, 1, 34));
        Button6.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Button6.setForeground(new java.awt.Color(255, 255, 255));
        Button6.setText("Home");
        Button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button6ActionPerformed(evt);
            }
        });

        Button5.setBackground(new java.awt.Color(1, 1, 34));
        Button5.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Button5.setForeground(new java.awt.Color(255, 255, 255));
        Button5.setText("Price Estimater");
        Button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button5ActionPerformed(evt);
            }
        });

        Button7.setBackground(new java.awt.Color(1, 1, 34));
        Button7.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Button7.setForeground(new java.awt.Color(255, 255, 255));
        Button7.setText("?");
        Button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(Button6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button6)
                    .addComponent(Button5)
                    .addComponent(Button7))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout BuildaPCLayout = new javax.swing.GroupLayout(BuildaPC);
        BuildaPC.setLayout(BuildaPCLayout);
        BuildaPCLayout.setHorizontalGroup(
            BuildaPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuildaPCLayout.createSequentialGroup()
                .addGroup(BuildaPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BuildaPCLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(82, 82, 82))
                    .addGroup(BuildaPCLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(93, 93, 93))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(BuildaPCLayout.createSequentialGroup()
                        .addGroup(BuildaPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(BuildaPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jComboBox4, javax.swing.GroupLayout.Alignment.LEADING, 0, 265, Short.MAX_VALUE)
                                .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(BuildaPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BuildaPCLayout.createSequentialGroup()
                        .addGroup(BuildaPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(BuildaPCLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(BuildaPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE))
                    .addGroup(BuildaPCLayout.createSequentialGroup()
                        .addGroup(BuildaPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(BuildaPCLayout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BuildaPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jComboBox9, javax.swing.GroupLayout.Alignment.LEADING, 0, 260, Short.MAX_VALUE)
                                .addComponent(jComboBox8, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        BuildaPCLayout.setVerticalGroup(
            BuildaPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuildaPCLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(BuildaPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BuildaPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(BuildaPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BuildaPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(BuildaPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BuildaPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(BuildaPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BuildaPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BuildaPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BuildaPCLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BuildaPCLayout.createSequentialGroup()
                        .addGroup(BuildaPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BuildaPCLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jPanel1.setBackground(new java.awt.Color(1, 1, 34));

        jPanel6.setBackground(new java.awt.Color(1, 5, 45));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel39.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Total :");

        Totalq.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        Totalq.setForeground(new java.awt.Color(255, 255, 255));

        jButton6.setBackground(new java.awt.Color(1, 1, 34));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Build a PC");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(1, 1, 34));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Home");

        jButton5.setBackground(new java.awt.Color(1, 1, 34));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("?");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(1, 1, 34));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Order");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Totalq, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Totalq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel39)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        jList1.setBackground(new java.awt.Color(1, 5, 45));
        jList1.setBorder(null);
        jList1.setForeground(new java.awt.Color(255, 255, 255));
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jComboBox5.setBackground(new java.awt.Color(1, 5, 45));
        jComboBox5.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Central Processing Unit", "Power Supply Unit", "Video Card", "External Hard Drive", "Motherboard", "Wireless Network Card", "Memory", "CPU Cooler" }));
        jComboBox5.setBorder(null);
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(1, 5, 45));

        listing16.setForeground(new java.awt.Color(255, 255, 255));

        listing15.setForeground(new java.awt.Color(255, 255, 255));

        listing14.setForeground(new java.awt.Color(255, 255, 255));

        listing13.setForeground(new java.awt.Color(255, 255, 255));

        listing12.setForeground(new java.awt.Color(255, 255, 255));

        listing11.setForeground(new java.awt.Color(255, 255, 255));

        listing10.setForeground(new java.awt.Color(255, 255, 255));

        listing9.setForeground(new java.awt.Color(255, 255, 255));

        listing8.setForeground(new java.awt.Color(255, 255, 255));

        listing5.setForeground(new java.awt.Color(255, 255, 255));

        listing6.setForeground(new java.awt.Color(255, 255, 255));

        listing7.setForeground(new java.awt.Color(255, 255, 255));

        listing3.setForeground(new java.awt.Color(255, 255, 255));
        listing3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listing3MouseClicked(evt);
            }
        });

        listing4.setForeground(new java.awt.Color(255, 255, 255));

        listing2.setForeground(new java.awt.Color(255, 255, 255));

        listing1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel8.setBackground(new java.awt.Color(1, 1, 34));

        selecteditem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selecteditem.setForeground(new java.awt.Color(255, 255, 255));

        Addbutton.setBackground(new java.awt.Color(1, 5, 45));
        Addbutton.setForeground(new java.awt.Color(255, 255, 255));
        Addbutton.setText("+ Add");
        Addbutton.setBorder(null);
        Addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(selecteditem, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(Addbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selecteditem, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Addbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listing1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(listing2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(listing4, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(listing3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(listing6, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(listing5, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(listing8, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(listing9, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(listing10, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(listing11, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(listing12, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(listing13, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(listing14, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(listing15, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(listing16, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(listing7, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(listing1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listing2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listing3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listing4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listing5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listing6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listing7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listing8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listing9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listing10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listing11, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listing12, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listing13, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listing14, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listing15, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(listing16, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout PriceExtimaterLayout = new javax.swing.GroupLayout(PriceExtimater);
        PriceExtimater.setLayout(PriceExtimaterLayout);
        PriceExtimaterLayout.setHorizontalGroup(
            PriceExtimaterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PriceExtimaterLayout.setVerticalGroup(
            PriceExtimaterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        HomePanel.setBackground(new java.awt.Color(1, 1, 34));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screen Shot 2024-05-08 at 7.11.46 AM.png"))); // NOI18N

        Button1.setBackground(new java.awt.Color(1, 1, 34));
        Button1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Button1.setForeground(new java.awt.Color(255, 255, 255));
        Button1.setText("Build a PC");
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });

        Button3.setBackground(new java.awt.Color(1, 1, 34));
        Button3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Button3.setForeground(new java.awt.Color(255, 255, 255));
        Button3.setText("Price Estimater");
        Button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button3ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(1, 1, 34));
        jButton7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Help");

        javax.swing.GroupLayout HomePanelLayout = new javax.swing.GroupLayout(HomePanel);
        HomePanel.setLayout(HomePanelLayout);
        HomePanelLayout.setHorizontalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomePanelLayout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button3, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HomePanelLayout.setVerticalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(BuildaPC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PriceExtimater, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(BuildaPC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PriceExtimater, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
        HomePanel.setVisible(false);
        BuildaPC.setVisible(true);

    }//GEN-LAST:event_Button1ActionPerformed

    private void Button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button5ActionPerformed
        BuildaPC.setVisible(false);
        PriceExtimater.setVisible(true);
    }//GEN-LAST:event_Button5ActionPerformed

    private void Button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button6ActionPerformed
        BuildaPC.setVisible(false);
        HomePanel.setVisible(true);
    }//GEN-LAST:event_Button6ActionPerformed

    private void Button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button3ActionPerformed
        HomePanel.setVisible(false);
        PriceExtimater.setVisible(true);
    }//GEN-LAST:event_Button3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        int pos = jComboBox1.getSelectedIndex();
        System.out.println(pos);
        CPUSelection fileInfo = new CPUSelection(pos);
        fileInfo.CpuReadName();
        fileInfo.setPrice();
        System.out.println(fileInfo.getPrice());

        order1.setText((String) jComboBox1.getSelectedItem());
        jComboBox1.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent ie) {
                String str = (String) jComboBox1.getSelectedItem();
                order1.setText(str);
            }
        });

        double p = fileInfo.getPrice();
        CPUPrice.setText("$"+p + "");

        total2 = Math.round((VCtrack + PSUtrack + Mtrack + Metrack + EHDtrack + WNCtrack + CPUCtrack + p) * 100.0) / 100.0;
        CPUtrack = p;

        TotalP.setText("$"+total2 + "");

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox1PopupMenuWillBecomeVisible

        jComboBox1.setModel(new DefaultComboBoxModel(fileInfo.CpuReadName()));
    }//GEN-LAST:event_jComboBox1PopupMenuWillBecomeVisible

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        int pos = jComboBox3.getSelectedIndex();
        System.out.println(pos);
        MSelection fileInfo5 = new MSelection(pos);
        fileInfo5.mReadName();
        fileInfo5.setPrice();
        System.out.println(fileInfo5.getPrice());

        order5.setText((String) jComboBox3.getSelectedItem());
        jComboBox3.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent ie) {
                String str = (String) jComboBox3.getSelectedItem();
                order5.setText(str);
            }
        });
        
        String order = jComboBox3.getSelectedItem().toString();
        

        double p = fileInfo5.getPrice();
        MPrice.setText("$"+p + "");

        total3 = Math.round((VCtrack + PSUtrack + CPUtrack + Metrack + EHDtrack + WNCtrack + CPUCtrack + p) * 100.0) / 100.0;
        Mtrack = p;

        TotalP.setText("$"+total3 + "");

    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        int pos = jComboBox6.getSelectedIndex();
        System.out.println(pos);
        PSUSelection fileInfo2 = new PSUSelection(pos);
        fileInfo2.PsuReadName();
        fileInfo2.setPrice();
        System.out.println(fileInfo2.getPrice());

        order2.setText((String) jComboBox6.getSelectedItem());
        jComboBox6.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent ie) {
                String str = (String) jComboBox6.getSelectedItem();
                order2.setText(str);
            }
        });
        double p = fileInfo2.getPrice();
        PSUPrice.setText("$"+p + "");

        total1 = Math.round((VCtrack + CPUtrack + Mtrack + Metrack + EHDtrack + WNCtrack + CPUCtrack + p) * 100.0) / 100.0;
        PSUtrack = p;

        TotalP.setText("$"+total1 + "");
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void jComboBox6PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox6PopupMenuWillBecomeVisible
        jComboBox6.setModel(new DefaultComboBoxModel(fileInfo2.PsuReadName()));
    }//GEN-LAST:event_jComboBox6PopupMenuWillBecomeVisible

    private void jComboBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox8ActionPerformed
        int pos = jComboBox8.getSelectedIndex();
        System.out.println(pos);
        WNCSelection fileInfo7 = new WNCSelection(pos);
        fileInfo7.wncReadName();
        fileInfo7.setPrice();
        System.out.println(fileInfo7.getPrice());

        order6.setText((String) jComboBox8.getSelectedItem());
        jComboBox8.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent ie) {
                String str = (String) jComboBox8.getSelectedItem();
                order6.setText(str);

            }
        });

        double p = fileInfo7.getPrice();
        WNCPrice.setText("$"+p + "");
        WNCtrack = p;

        TotalP.setText("");
        total6 = Math.round((PSUtrack + CPUtrack + Mtrack + Metrack + VCtrack + EHDtrack + CPUCtrack + p) * 100.0) / 100.0;
        TotalP.setText("$"+total6 + "");

    }//GEN-LAST:event_jComboBox8ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        int pos = jComboBox2.getSelectedIndex();
        System.out.println(pos);
        VCSelection fileInfo3 = new VCSelection(pos);
        fileInfo3.vcReadName();
        fileInfo3.setPrice();
        System.out.println(fileInfo3.getPrice());

        order3.setText((String) jComboBox2.getSelectedItem());
        jComboBox2.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent ie) {
                String str = (String) jComboBox2.getSelectedItem();
                order3.setText(str);

            }
        });

        double p = fileInfo3.getPrice();
        VCPrice.setText("$"+p + "");
        VCtrack = p;

        TotalP.setText("");
        total = Math.round((PSUtrack + CPUtrack + Mtrack + Metrack + EHDtrack + WNCtrack + CPUCtrack + p) * 100.0) / 100.0;
        TotalP.setText("$"+total + "");


    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox2PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox2PopupMenuWillBecomeVisible
        jComboBox2.setModel(new DefaultComboBoxModel(fileInfo3.vcReadName()));
    }//GEN-LAST:event_jComboBox2PopupMenuWillBecomeVisible

    private void jComboBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox7ActionPerformed
        int pos = jComboBox7.getSelectedIndex();
        System.out.println(pos);
        EHDSelection fileInfo4 = new EHDSelection(pos);
        fileInfo4.ehdReadName();
        fileInfo4.setPrice();
        System.out.println(fileInfo4.getPrice());

        order4.setText((String) jComboBox7.getSelectedItem());
        jComboBox7.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent ie) {
                String str = (String) jComboBox7.getSelectedItem();
                order4.setText(str);

            }
        });

        double p = fileInfo4.getPrice();
        EHDPrice.setText("$"+p + "");
        EHDtrack = p;

        TotalP.setText("");
        total5 = Math.round((PSUtrack + CPUtrack + Mtrack + Metrack + WNCtrack + VCtrack + CPUCtrack + p) * 100.0) / 100.0;
        TotalP.setText("$"+total5 + "");

    }//GEN-LAST:event_jComboBox7ActionPerformed

    private void jComboBox7PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox7PopupMenuWillBecomeVisible
        jComboBox7.setModel(new DefaultComboBoxModel(fileInfo4.ehdReadName()));
    }//GEN-LAST:event_jComboBox7PopupMenuWillBecomeVisible

    private void jComboBox3PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox3PopupMenuWillBecomeVisible
        jComboBox3.setModel(new DefaultComboBoxModel(fileInfo5.mReadName()));
    }//GEN-LAST:event_jComboBox3PopupMenuWillBecomeVisible

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        int pos = jComboBox4.getSelectedIndex();
        System.out.println(pos);
        MeSelection fileInfo6 = new MeSelection(pos);
        fileInfo6.meReadName();
        fileInfo6.setPrice();
        System.out.println(fileInfo6.getPrice());

        order7.setText((String) jComboBox4.getSelectedItem());
        jComboBox4.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent ie) {
                String str = (String) jComboBox4.getSelectedItem();
                order7.setText(str);

            }
        });

        double p = fileInfo6.getPrice();
        MePrice.setText("$"+p + "");
        Metrack = p;

        TotalP.setText("");
        total4 = Math.round((PSUtrack + CPUtrack + Mtrack + VCtrack + WNCtrack + EHDtrack + CPUCtrack + p) * 100.0) / 100.0;
        TotalP.setText("$"+total4 + "");
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox4PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox4PopupMenuWillBecomeVisible
        jComboBox4.setModel(new DefaultComboBoxModel(fileInfo6.meReadName()));
    }//GEN-LAST:event_jComboBox4PopupMenuWillBecomeVisible

    private void jComboBox8PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox8PopupMenuWillBecomeVisible
        jComboBox8.setModel(new DefaultComboBoxModel(fileInfo7.wncReadName()));
    }//GEN-LAST:event_jComboBox8PopupMenuWillBecomeVisible

    private void jComboBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox9ActionPerformed
        int pos = jComboBox9.getSelectedIndex();
        System.out.println(pos);
        MeSelection fileInfo8 = new MeSelection(pos);
        fileInfo8.meReadName();
        fileInfo8.setPrice();
        System.out.println(fileInfo8.getPrice());

        order8.setText((String) jComboBox9.getSelectedItem());
        jComboBox9.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent ie) {
                String str = (String) jComboBox9.getSelectedItem();
                order8.setText(str);

            }
        });

        double p = fileInfo8.getPrice();
        CPUCPrice.setText("$"+p + "");
        CPUCtrack = p;

        TotalP.setText("");
        total7 = Math.round((PSUtrack + CPUtrack + Mtrack + VCtrack + WNCtrack + EHDtrack + Metrack + p) * 100.0) / 100.0;
        TotalP.setText("$"+total7 + "");
    }//GEN-LAST:event_jComboBox9ActionPerformed

    private void jComboBox9PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox9PopupMenuWillBecomeVisible
        jComboBox9.setModel(new DefaultComboBoxModel(fileInfo8.cpucReadName()));
    }//GEN-LAST:event_jComboBox9PopupMenuWillBecomeVisible

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jList1ValueChanged

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        int pos = jComboBox5.getSelectedIndex();
        int num = pos;
        ArrayList<String> noPrice = new ArrayList<>();

        if (num == 0) {
            DefaultListModel<String> DLM = new DefaultListModel<>();
            CPUSelection fileinfo = new CPUSelection();
            fileinfo.CpuReadName();

            String[] cpunameInfo = fileinfo.nameArray;
            String[] cpupriceInfo = fileinfo.priceArray;

            if (cpunameInfo != null && cpupriceInfo != null && cpunameInfo.length == cpupriceInfo.length) {
                for (int i = 0; i < cpunameInfo.length; i++) {
                    DLM.addElement(cpunameInfo[i] + "  -   $" + cpupriceInfo[i] + " ");
                }
            } else {
                System.out.println("Arrays are null or have different lengths.");
            }

            jList1.setModel(DLM);
        } else if (num == 1) {
            DefaultListModel<String> DLM = new DefaultListModel<>();
            PSUSelection fileinfo = new PSUSelection();
            fileinfo.PsuReadName();

            String[] psunameInfo = fileinfo.nameArray;
            String[] psupriceInfo = fileinfo.priceArray;

            if (psunameInfo != null && psupriceInfo != null && psunameInfo.length == psupriceInfo.length) {
                for (int i = 0; i < psunameInfo.length; i++) {
                    if (psupriceInfo[i].equals("")) {
                        noPrice.add(psunameInfo[i]);
                    } else {
                        DLM.addElement(psunameInfo[i] + "  -   $" + psupriceInfo[i] + " ");
                    }
                }
            } else {
                System.out.println("Arrays are null or have different lengths.");
            }

            jList1.setModel(DLM);
        } else if (num == 2) {
            DefaultListModel<String> DLM = new DefaultListModel<>();
            VCSelection fileinfo = new VCSelection();
            fileinfo.vcReadName();

            String[] psunameInfo = fileinfo.nameArray;
            String[] psupriceInfo = fileinfo.priceArray;

            if (psunameInfo != null && psupriceInfo != null && psunameInfo.length == psupriceInfo.length) {
                for (int i = 0; i < psunameInfo.length; i++) {
                    if (psupriceInfo[i].equals("")) {
                        noPrice.add(psunameInfo[i]);
                    } else {
                        DLM.addElement(psunameInfo[i] + "  -   $" + psupriceInfo[i] + " ");
                    }
                }
            } else {
                System.out.println("Arrays are null or have different lengths.");
            }

            jList1.setModel(DLM);
        } else if (num == 3) {
            DefaultListModel<String> DLM = new DefaultListModel<>();
            EHDSelection fileinfo = new EHDSelection();
            fileinfo.ehdReadName();

            String[] psunameInfo = fileinfo.nameArray;
            String[] psupriceInfo = fileinfo.priceArray;

            if (psunameInfo != null && psupriceInfo != null && psunameInfo.length == psupriceInfo.length) {
                for (int i = 0; i < psunameInfo.length; i++) {
                    if (psupriceInfo[i].equals("")) {
                        noPrice.add(psunameInfo[i]);
                    } else {
                        DLM.addElement(psunameInfo[i] + "  -   $" + psupriceInfo[i] + " ");
                    }
                }
            } else {
                System.out.println("Arrays are null or have different lengths.");
            }

            jList1.setModel(DLM);

        } else if (num == 4) {
            DefaultListModel<String> DLM = new DefaultListModel<>();
            MSelection fileinfo = new MSelection();
            fileinfo.mReadName();

            String[] psunameInfo = fileinfo.nameArray;
            String[] psupriceInfo = fileinfo.priceArray;

            if (psunameInfo != null && psupriceInfo != null && psunameInfo.length == psupriceInfo.length) {
                for (int i = 0; i < psunameInfo.length; i++) {
                    if (psupriceInfo[i].equals("")) {
                        noPrice.add(psunameInfo[i]);
                    } else {
                        DLM.addElement(psunameInfo[i] + "  -   $" + psupriceInfo[i] + " ");
                    }
                }
            } else {
                System.out.println("Arrays are null or have different lengths.");
            }

            jList1.setModel(DLM);
        } else if (num == 5) {
            DefaultListModel<String> DLM = new DefaultListModel<>();
            WNCSelection fileinfo = new WNCSelection();
            fileinfo.wncReadName();

            String[] psunameInfo = fileinfo.nameArray;
            String[] psupriceInfo = fileinfo.priceArray;

            if (psunameInfo != null && psupriceInfo != null && psunameInfo.length == psupriceInfo.length) {
                for (int i = 0; i < psunameInfo.length; i++) {
                    if (psupriceInfo[i].equals("")) {
                        noPrice.add(psunameInfo[i]);
                    } else {
                        DLM.addElement(psunameInfo[i] + "  -   $" + psupriceInfo[i] + " ");
                    }
                }
            } else {
                System.out.println("Arrays are null or have different lengths.");
            }

            jList1.setModel(DLM);
        } else if (num == 6) {
            DefaultListModel<String> DLM = new DefaultListModel<>();
            MeSelection fileinfo = new MeSelection();
            fileinfo.meReadName();

            String[] psunameInfo = fileinfo.nameArray;
            String[] psupriceInfo = fileinfo.priceArray;

            if (psunameInfo != null && psupriceInfo != null && psunameInfo.length == psupriceInfo.length) {
                for (int i = 0; i < psunameInfo.length; i++) {
                    if (psupriceInfo[i].equals("")) {
                        noPrice.add(psunameInfo[i]);
                    } else {
                        DLM.addElement(psunameInfo[i] + "  -   $" + psupriceInfo[i] + " ");
                    }
                }
            } else {
                System.out.println("Arrays are null or have different lengths.");
            }

            jList1.setModel(DLM);
        } else if (num == 7) {
            DefaultListModel<String> DLM = new DefaultListModel<>();
            CPUCSelection fileinfo = new CPUCSelection();
            fileinfo.cpucReadName();

            String[] psunameInfo = fileinfo.nameArray;
            String[] psupriceInfo = fileinfo.priceArray;

            if (psunameInfo != null && psupriceInfo != null && psunameInfo.length == psupriceInfo.length) {
                for (int i = 0; i < psunameInfo.length; i++) {
                    if (psupriceInfo[i].equals("")) {
                        noPrice.add(psunameInfo[i]);
                    } else {
                        DLM.addElement(psunameInfo[i] + "  -   $" + psupriceInfo[i] + " ");
                    }
                }
            } else {
                System.out.println("Arrays are null or have different lengths.");
            }

            jList1.setModel(DLM);
        }

        jList1.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                String selectedItem = jList1.getSelectedValue();
                selecteditem.setText(selectedItem);
            }
        });

    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void AddbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbuttonActionPerformed
      String text = selecteditem.getText();

Pattern pattern = Pattern.compile("\\$(\\d+[\\.\\d+]*)");
Matcher matcher = pattern.matcher(text);

boolean labelFound = false;

while (currentLabelIndex < labels.length &&!labelFound) {
    if (labels[currentLabelIndex].getText().isEmpty()) {
        labels[currentLabelIndex].setText(text.replaceAll("- +\\$[0-9]+\\.[0-9]+", ""));
        labelFound = true;
    }
    currentLabelIndex++;
    
}

if (labelFound) {
    double tempTotalPrice = 0.0; 
    while (matcher.find()) {
        String priceStr = matcher.group(1); 
        double priceInt = Double.parseDouble(priceStr);
        System.out.println(priceInt);
        System.out.println(priceStr);
        tempTotalPrice += priceInt; 
    }
    totalPrice += tempTotalPrice; 
    totalPrice = Math.round(totalPrice * 100.0) / 100.0;
    System.out.println("Total price: " + totalPrice); 

    double thetotal = totalPrice;
    Totalq.setText("$" + thetotal + "");
    totalPrice1 = thetotal;
}

if (currentLabelIndex >= labels.length) {
    currentLabelIndex = 0; 
}
    }//GEN-LAST:event_AddbuttonActionPerformed

    private void listing3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listing3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_listing3MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        while (currentLabelIndex < order.length) {
            if (!order[currentLabelIndex].getText().isEmpty()) {
                
                Orders.add(order[currentLabelIndex].getText());
                
            }
            currentLabelIndex++;
        }
        
        while (currentLabelIndex <= 16) {
            if (!labels[currentLabelIndex].getText().isEmpty()) {
                
                Orders.add(labels[currentLabelIndex].getText());
                
            }
            currentLabelIndex++;
        }
        
       Orderer = Orders.toArray(new String[Orders.size()]);
       
        BuildaPC.setVisible(false);
        OrderTab li = new OrderTab();
        li.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         BuildaPC.setVisible(true);
        PriceExtimater.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       EstimaterHelp li = new EstimaterHelp();
        li.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void Button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button7ActionPerformed
         BuildaPCHelp li = new BuildaPCHelp();
        li.setVisible(true);
    }//GEN-LAST:event_Button7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        while (currentLabelIndex < order.length) {
            if (!order[currentLabelIndex].getText().isEmpty()) {
                
                Orders.add(order[currentLabelIndex].getText());
                
            }
            currentLabelIndex++;
        }
        
        while (currentLabelIndex < labels.length) {
            if (!labels[currentLabelIndex].getText().isEmpty()) {
                
                Orders.add(labels[currentLabelIndex].getText());
                
            }
            currentLabelIndex++;
        }
        
       Orderer = Orders.toArray(new String[Orders.size()]);
       
        BuildaPC.setVisible(false);
        OrderTab li = new OrderTab();
        li.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addbutton;
    private javax.swing.JPanel BuildaPC;
    private javax.swing.JButton Button1;
    private javax.swing.JButton Button3;
    private javax.swing.JButton Button5;
    private javax.swing.JButton Button6;
    private javax.swing.JButton Button7;
    private javax.swing.JLabel CPUCPrice;
    private javax.swing.JLabel CPUPrice;
    private javax.swing.JLabel EHDPrice;
    private javax.swing.JPanel HomePanel;
    private javax.swing.JLabel MPrice;
    private javax.swing.JLabel MePrice;
    private javax.swing.JLabel PSUPrice;
    private javax.swing.JPanel PriceExtimater;
    private javax.swing.JLabel TotalP;
    private javax.swing.JLabel Totalq;
    private javax.swing.JLabel VCPrice;
    private javax.swing.JLabel WNCPrice;
    private javax.swing.JLabel item;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel listing1;
    private javax.swing.JLabel listing10;
    private javax.swing.JLabel listing11;
    private javax.swing.JLabel listing12;
    private javax.swing.JLabel listing13;
    private javax.swing.JLabel listing14;
    private javax.swing.JLabel listing15;
    private javax.swing.JLabel listing16;
    private javax.swing.JLabel listing2;
    private javax.swing.JLabel listing3;
    private javax.swing.JLabel listing4;
    private javax.swing.JLabel listing5;
    private javax.swing.JLabel listing6;
    private javax.swing.JLabel listing7;
    private javax.swing.JLabel listing8;
    private javax.swing.JLabel listing9;
    private javax.swing.JLabel order1;
    private javax.swing.JLabel order2;
    private javax.swing.JLabel order3;
    private javax.swing.JLabel order4;
    private javax.swing.JLabel order5;
    private javax.swing.JLabel order6;
    private javax.swing.JLabel order7;
    private javax.swing.JLabel order8;
    private javax.swing.JLabel selecteditem;
    // End of variables declaration//GEN-END:variables

    private void close() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
