/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalpcbuild;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.util.regex.Matcher;
import java.util.regex.Pattern;


/**
 *
 * @author 
 */
public class Registration extends javax.swing.JFrame {

    
    /**
     * Creates new form Login
     */
    public Registration() {
        
        initComponents();
        ClearErrorLabels();
        ClearField();
    }
    
    public void close(){
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    
     private void ClearErrorLabels() {
        DateError.setText("");
        GmailError.setText("");
        NameError.setText("");
        SurnameError.setText("");
        PasswordError.setText("");
        Overall.setText("");
    }
     
     private void ClearField() {
        txfGmail.setText("");
        txfNames.setText("");
        txfSurname.setText("");
        txfPassword.setText("");
    }
     
    private boolean presenceAndLengthCheck(javax.swing.JTextField txf,javax.swing.JLabel lbl) {
        
       if (txf == null || txf.getText() == null || txf.getText().length() <= 5) {
        lbl.setText("Invalid");
        return false;
    }
    lbl.setText("");
    return true;
    }
    
    private boolean typecheck(javax.swing.JTextField txf, javax.swing.JLabel lbl, String validStr) {
           String txfText = txf.getText();
    for (int i = 0; i < txfText.length(); i++) {
        if (!Character.isLetterOrDigit(txfText.charAt(i)) && !(validStr.indexOf(txfText.charAt(i)) >= 0)) {
            lbl.setText("Invalid");
            return false;
            }
        }
    return true;
    }
    
     private boolean Gmailcheck(javax.swing.JTextField txf, javax.swing.JLabel lbl) {
            String txfText = txf.getText();
            String regex = "^[\\w!#$%&amp;'*+/=?`{|}~^-]+(?:\\.[\\w!#$%&amp;'*+/=?`{|}~^-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$";
        Pattern pattern = Pattern.compile(regex);
        
        Matcher match=pattern.matcher(txf.getText());
            for (int i = 0; i < txfText.length(); i++) {
                if(txf == null || txf.getText().length() <= 1 || !match.matches()) {
            lbl.setText("Invalid");
                }
                
            return false;
        }
            
        return true;
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txfNames = new javax.swing.JTextField();
        txfSurname = new javax.swing.JTextField();
        txfGmail = new javax.swing.JTextField();
        txfPassword = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        SurnameLabel = new javax.swing.JLabel();
        GmailLabel = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        User = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        SurnameError = new javax.swing.JLabel();
        NameError = new javax.swing.JLabel();
        GmailError = new javax.swing.JLabel();
        PasswordError = new javax.swing.JLabel();
        DateError = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        LoginWindow = new javax.swing.JButton();
        Overall = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        jLabel10.setForeground(new java.awt.Color(255, 0, 51));
        jLabel10.setText("Invalid");

        jButton3.setText("End");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(1, 1, 34));

        jPanel2.setBackground(new java.awt.Color(1, 1, 64));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registration");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(jLabel1)
                .addContainerGap(233, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );

        txfNames.setBackground(new java.awt.Color(1, 1, 64));
        txfNames.setForeground(new java.awt.Color(255, 255, 255));
        txfNames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfNamesActionPerformed(evt);
            }
        });
        txfNames.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txfNamesKeyReleased(evt);
            }
        });

        txfSurname.setBackground(new java.awt.Color(1, 1, 64));
        txfSurname.setForeground(new java.awt.Color(255, 255, 255));
        txfSurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfSurnameActionPerformed(evt);
            }
        });
        txfSurname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txfSurnameKeyReleased(evt);
            }
        });

        txfGmail.setBackground(new java.awt.Color(1, 1, 64));
        txfGmail.setForeground(new java.awt.Color(255, 255, 255));
        txfGmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfGmailActionPerformed(evt);
            }
        });
        txfGmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txfGmailKeyReleased(evt);
            }
        });

        txfPassword.setBackground(new java.awt.Color(1, 1, 64));
        txfPassword.setForeground(new java.awt.Color(255, 255, 255));
        txfPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txfPasswordKeyReleased(evt);
            }
        });

        jRadioButton1.setBackground(new java.awt.Color(1, 1, 34));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Male");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setBackground(new java.awt.Color(1, 1, 34));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Female");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        SurnameLabel.setForeground(new java.awt.Color(255, 255, 255));
        SurnameLabel.setText("User Surname :");

        GmailLabel.setForeground(new java.awt.Color(255, 255, 255));
        GmailLabel.setText("User Gmail :");

        NameLabel.setForeground(new java.awt.Color(255, 255, 255));
        NameLabel.setText("User Name :");

        User.setForeground(new java.awt.Color(255, 255, 255));
        User.setText("Password:");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Gender :");

        SurnameError.setForeground(new java.awt.Color(255, 0, 51));

        NameError.setForeground(new java.awt.Color(255, 0, 51));

        GmailError.setForeground(new java.awt.Color(255, 0, 51));

        PasswordError.setForeground(new java.awt.Color(255, 0, 51));

        DateError.setForeground(new java.awt.Color(255, 0, 51));

        jButton1.setBackground(new java.awt.Color(1, 1, 34));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton1KeyReleased(evt);
            }
        });

        LoginWindow.setBackground(new java.awt.Color(1, 1, 34));
        LoginWindow.setForeground(new java.awt.Color(255, 255, 255));
        LoginWindow.setText("Login");
        LoginWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginWindowActionPerformed(evt);
            }
        });

        Overall.setForeground(new java.awt.Color(255, 0, 51));
        Overall.setText("Invalid Info");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(231, 231, 231)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txfGmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txfSurname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGap(213, 213, 213)
                                    .addComponent(txfNames, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(NameLabel)
                                    .addComponent(SurnameLabel)
                                    .addComponent(GmailLabel)
                                    .addComponent(User)
                                    .addComponent(jLabel7))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jRadioButton1)
                                    .addComponent(jRadioButton2))))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SurnameError)
                            .addComponent(GmailError)
                            .addComponent(NameError)
                            .addComponent(PasswordError)
                            .addComponent(DateError)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LoginWindow)
                                .addGap(415, 415, 415)
                                .addComponent(Overall, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txfNames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NameError, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txfSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SurnameError, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txfGmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GmailError, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PasswordError, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SurnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(GmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(User, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DateError, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(Overall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LoginWindow))
                .addGap(20, 20, 20))
        );

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void txfSurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfSurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfSurnameActionPerformed

    private void txfNamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfNamesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfNamesActionPerformed

    private void txfGmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfGmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfGmailActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void LoginWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginWindowActionPerformed
        close();
        Login li = new Login();
        li.setVisible(true);
    }//GEN-LAST:event_LoginWindowActionPerformed

    private void txfNamesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfNamesKeyReleased
        // TODO add your handling code here:
        String PATTERN = "[a-zA-Z]{5,30}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(txfNames.getText());
        
        if(!match.matches()){
            NameError.setText("!");
        }else{
            NameError.setText(null);
        }
    }//GEN-LAST:event_txfNamesKeyReleased

    private void txfGmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfGmailKeyReleased
        // TODO add your handling code here:
        String regex = "^[\\w!#$%&amp;'*+/=?`{|}~^-]+(?:\\.[\\w!#$%&amp;'*+/=?`{|}~^-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$";
        Pattern pattern = Pattern.compile(regex);
        
        Matcher match=pattern.matcher(txfGmail.getText());
        if (!match.matches() )
        {
            GmailError.setText("!");
        }
        else
        {
            GmailError.setText(null);
        }
    }//GEN-LAST:event_txfGmailKeyReleased

    private void txfSurnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfSurnameKeyReleased
        // TODO add your handling code here:
        String PATTERN = "[a-zA-Z]{5,30}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(txfSurname.getText());
        
        if(!match.matches()){
            SurnameError.setText("!");
        }else{
            SurnameError.setText(null);
        }
    }//GEN-LAST:event_txfSurnameKeyReleased

    private void txfPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfPasswordKeyReleased
        // TODO add your handling code here:
        String regExpn = "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=\\S+$).{8,20}$";

    Pattern pattern = Pattern.compile(regExpn, Pattern.CASE_INSENSITIVE);
    Matcher matcher = pattern.matcher(txfPassword.getText());

    if(!matcher.matches()){
            PasswordError.setText("!");
        }else{
            PasswordError.setText(null);
        }
    }//GEN-LAST:event_txfPasswordKeyReleased

    private void jButton1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        ClearErrorLabels();
        if (validName() && validSurname() && validGmail()) {
            this.toBack();
            setVisible(false);
            AdvancedInfo ai = new AdvancedInfo();
            ai.toFront();
            ai.setVisible(true);
        }
        }

        private boolean validName() {
            String name = txfNames.getText();
            if (name == null || name.length() <= 5) {
                Overall.setText("Invalid");
                return false;
            }
            return true;
        }

        private boolean validSurname() {
            String surname = txfSurname.getText();
            if (surname == null || surname.length() <= 5) {
                Overall.setText("Invalid");
                return false;
            }
            return true;
        }

        private boolean validGmail() {
            String gmail = txfGmail.getText();
            String regex = "^[\\w!#$%&amp;'*+/=?`{|}~^-]+(?:\\.[\\w!#$%&amp;'*+/=?`{|}~^-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$";
            Pattern pattern = Pattern.compile(regex);
            Matcher match = pattern.matcher(gmail);
            if (!match.matches()) {
                Overall.setText("Invalid");
                return false;
            }
            return true;

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DateError;
    private javax.swing.JLabel GmailError;
    private javax.swing.JLabel GmailLabel;
    private javax.swing.JButton LoginWindow;
    private javax.swing.JLabel NameError;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel Overall;
    private javax.swing.JLabel PasswordError;
    private javax.swing.JLabel SurnameError;
    private javax.swing.JLabel SurnameLabel;
    private javax.swing.JLabel User;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField txfGmail;
    private javax.swing.JTextField txfNames;
    private javax.swing.JTextField txfPassword;
    private javax.swing.JTextField txfSurname;
    // End of variables declaration//GEN-END:variables
}


